title: Rares Finatan # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Digital analytics specialist with 9+ years of experience working across automotive, retail, consumer packaged goods, pharmaceutical, and non-profit verticals. 
  <br><br>
  Primarily working in Python, R, GCP, and SQL for data analytics projects.
  <br><br>
  <a href="https://www.linkedin.com/in/rfinatan/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://raresfin.medium.com/">Read My Medium Publications</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
